# fpl_v2 driver
Thin notebook over the package. All logic lives in the modules; this just runs and inspects.

Run jupyter from the repo root so `import fpl_v2` resolves (`uv run jupyter lab`).

In [1]:
# Ensure the repo root (the dir containing fpl_v2/) is importable, whatever the launch dir.
import sys, pathlib
root = pathlib.Path.cwd()
while not (root / 'fpl_v2').is_dir() and root != root.parent:
    root = root.parent
if str(root) not in sys.path:
    sys.path.insert(0, str(root))

In [2]:
from fpl_v2 import pipeline, config

forecast, squad = pipeline.run(save=True)  # refresh=True to re-pull live data
forecast.shape

[07/26/26 21:17:49] INFO     No custom team name replacements found. You can configure these in       ]8;id=5178083;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=5178084;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_config.py#91\91]8;;\
                             /home/peter/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=5178090;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=5178091;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_config.py#189\189]8;;\
                             /home/peter/soccerdata/config/league_dict.json.

                    INFO     Saving cached data to                                                   ]8;id=5178098;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5178099;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\
                             /home/peter/coding/football_stuff/fpl_v2/data/raw/understat_match

[2026-07-26 21:17:49] INFO     TLSLibrary:_load_library:397 - Successfully loaded TLS library: /home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/tls_requests/bin/tls-client-xgo-1.13.1-linux-amd64.so

                    INFO     Successfully loaded TLS library:                                      ]8;id=5178106;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/tls_requests/models/libraries.py\libraries.py]8;;\:]8;id=5178107;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/tls_requests/models/libraries.py#397\397]8;;\
                             /home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/
                             tls_requests/bin/tls-client-xgo-1.13.1-linux-amd64.so

[07/26/26 21:17:50] INFO     Saving cached data to                                                   ]8;id=5178112;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5178113;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\
                             /home/peter/coding/football_stuff/fpl_v2/data/raw/understat_match

(425, 33)

In [3]:
cols = ['web_name', 'team_name', 'position', 'cost', 'xG', 'xAG', 'xClean', 'xBadGames',
        'expected_defcon_points', 'expected_appearance_points', 'xPoints']
forecast.sort_values('xPoints', ascending=False)[cols].head(30)

,web_name,team_name,position,cost,xG,xAG,xClean,xBadGames,expected_defcon_points,expected_appearance_points,xPoints
241,Virgil,Liverpool,DEF,65,3.77,1.44,16.0,9.0,33.988759,76.0,191.928759
0,Gabriel,Arsenal,DEF,80,2.94,1.75,26.0,3.0,25.740922,62.0,191.844372
309,B.Fernandes,Man Utd,MID,120,10.79,12.28,12.0,5.0,9.890561,69.0,180.434947
373,Senesi,Spurs,DEF,60,1.53,4.72,12.0,10.0,45.847120,74.0,179.720453
294,Haaland,Man City,FWD,155,25.50,2.67,17.0,6.0,0.007776,68.0,178.017776
271,Guéhi,Man City,DEF,60,4.05,2.37,17.0,6.0,19.341800,70.0,177.857064
371,Van Hecke,Spurs,DEF,50,3.31,1.57,12.0,10.0,34.828128,72.0,167.064795
295,Anderson,Man City,MID,65,2.94,4.79,17.0,6.0,44.952980,75.0,165.585553
94,Thiago,Brentford,FWD,80,20.60,1.83,13.0,10.0,1.260713,75.0,164.150713
1,J.Timber,Arsenal,DEF,65,4.71,1.53,26.0,3.0,2.743052,56.0,164.005918
9,Rice,Arsenal,MID,75,3.15,7.32,26.0,3.0,28.432953,71.0,160.656988
180,Tarkowski,Everton,DEF,60,2.53,2.10,9.0,12.0,41.601834,74.0,160.450255
154,Lacroix,Crystal Palace,DEF,60,2.45,0.83,11.0,11.0,43.652061,69.0,159.609605
140,Enzo,Chelsea,MID,70,11.26,7.26,7.0,13.0,3.856835,71.0,159.310519
270,O'Reilly,Man City,DEF,65,6.12,2.67,17.0,6.0,4.371557,62.0,159.015592
52,Truffert,Bournemouth,DEF,55,1.35,3.07,14.0,12.0,21.454273,76.0,158.223922
325,Thiaw,Newcastle,DEF,50,4.80,0.96,12.0,10.0,26.034137,67.0,157.636359
124,Struijk,Brighton,DEF,50,3.06,0.76,16.0,10.0,24.104389,66.0,157.086494
189,Garner,Everton,MID,60,2.10,6.18,9.0,12.0,41.503601,76.0,155.525180
280,Semenyo,Man City,MID,85,11.10,3.12,17.0,6.0,2.747038,72.0,155.513470
73,Collins,Brentford,DEF,55,2.24,1.71,13.0,10.0,32.966064,67.0,155.022029
2,Saliba,Arsenal,DEF,60,0.88,1.21,26.0,3.0,7.865319,59.0,152.972395
253,Szoboszlai,Liverpool,MID,70,4.76,6.83,16.0,9.0,17.144260,72.0,148.554728
310,Mbeumo,Man Utd,MID,80,11.98,4.99,12.0,5.0,0.228368,64.0,148.259772
97,F.Kadıoğlu,Brighton,DEF,45,2.06,3.31,16.0,10.0,1.944201,72.0,145.655254
60,Scott,Bournemouth,MID,60,3.80,2.94,14.0,12.0,35.495854,70.0,144.974334
74,Van den Berg,Brentford,DEF,50,3.36,1.45,13.0,10.0,24.234760,62.0,144.651778
156,Richards,Crystal Palace,DEF,50,2.42,1.56,11.0,11.0,33.303866,64.0,143.762638
83,Schade,Brentford,MID,60,12.08,2.05,13.0,10.0,1.575416,65.0,143.555825
59,Tavernier,Bournemouth,MID,60,9.06,4.60,14.0,12.0,8.031315,65.0,143.314941

In [4]:
squad_cols = ['web_name', 'team_name', 'position', 'cost', 'xPoints']
print(f"{squad.formation}  |  £{squad.total_cost/10:.1f}m  |  total xP (capt x2): {squad.total_xpoints:.1f}")
print('Captain:', squad.captain['web_name'])
squad.players.sort_values(['position', 'xPoints'], ascending=[True, False])[squad_cols]

5-4-1  |  £78.5m  |  total xP (capt x2): 2123.2

Captain:

Raya

        web_name  team_name position  cost     xPoints
241       Virgil  Liverpool      DEF    65  191.928759
0        Gabriel    Arsenal      DEF    80  191.844372
373       Senesi      Spurs      DEF    60  179.720453
271        Guéhi   Man City      DEF    60  177.857064
371    Van Hecke      Spurs      DEF    50  167.064795
94        Thiago  Brentford      FWD    80  164.150713
425         Raya    Arsenal       GK    60  192.322105
309  B.Fernandes    Man Utd      MID   120  180.434947
295     Anderson   Man City      MID    65  165.585553
9           Rice    Arsenal      MID    75  160.656988
140         Enzo    Chelsea      MID    70  159.310519

## Tweaking
- Scoring weights: `config.POINTS_FOR_GOAL`, `POINTS_FOR_ASSIST`, `POINTS_FOR_CLEAN`, `POINTS_FOR_CONCEDED`
- Clean-sheet / bad-defensive-game thresholds: `config.CLEAN_SHEET_XGA_THRESHOLD`, `BAD_DEFENSIVE_GAME_XGA_THRESHOLD`
- Appearance points: `config.APPEARANCE_POINTS_SHORT`, `APPEARANCE_POINTS_FULL` (carried forward from last season as-is, not reprojected)
- Formations / budgets: `config.FORMATIONS`
- Multi-season blend: `config.BLEND_WEIGHTS`
- Manual fixes: `overrides.OVERRIDES`

e.g. re-run a single formation:

## Goalkeepers
GK xPoints ranking (the keeper is also folded into the squad optimiser above).

In [5]:
from fpl_v2 import goalkeepers

goalkeepers.rank().head(10)

[07/26/26 21:17:51] INFO     Saving cached data to                                                   ]8;id=5178118;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5178119;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\
                             /home/peter/coding/football_stuff/fpl_v2/data/raw/understat_match

,web_name,team_name,now_cost,s90,saves_per_90,xClean,xBadGames,expected_appearance_points,GK_xPoints
0,Raya,Arsenal,60,37.0,1.62,26.0,3.0,74.0,192.322105
1,Verbruggen,Brighton,45,38.0,2.79,16.0,10.0,76.0,165.340000
2,Petrović,Bournemouth,45,38.0,2.87,14.0,12.0,76.0,156.353333
3,Kelleher,Brentford,50,37.0,2.95,13.0,10.0,74.0,151.278070
4,Donnarumma,Man City,55,34.0,2.29,17.0,6.0,68.0,149.427018
5,Dubravka,Spurs,40,35.0,3.63,12.0,10.0,70.0,147.350000
6,Henderson,Crystal Palace,50,37.0,2.86,11.0,11.0,74.0,141.404912
7,Leno,Fulham,45,38.0,2.58,10.0,11.0,76.0,137.680000
8,Pickford,Everton,55,38.0,2.63,9.0,12.0,76.0,133.313333
9,Roefs,Sunderland,50,35.0,3.11,9.0,10.0,70.0,130.230702

## Defensive contribution & transfers
Expected DefCon points (in `xPoints`), plus movers flagged for manual review.

In [6]:
dc = ['web_name', 'team_name', 'position', 'expected_defcon_points', 'is_mover', 'defcon_multiplier']
print('Top defensive-contribution scorers:')
print(forecast.sort_values('expected_defcon_points', ascending=False)[dc].head(8).to_string(index=False))
print('\nTransferred players flagged for manual review (multiplier < 1 = moved to a less defensive side):')
forecast[forecast['is_mover']].sort_values('defcon_multiplier')[dc]

Top defensive-contribution scorers:

 web_name      team_name position  expected_defcon_points  is_mover  defcon_multiplier
   Senesi          Spurs      DEF               45.847120      True           0.934024
 Anderson       Man City      MID               44.952980      True           0.907172
  Lacroix Crystal Palace      DEF               43.652061     False           1.000000
Tarkowski        Everton      DEF               41.601834     False           1.000000
   Garner        Everton      MID               41.503601     False           1.000000
   Ampadu          Leeds      MID               37.347780     False           1.000000
 Andersen         Fulham      DEF               36.880747     False           1.000000
    Scott    Bournemouth      MID               35.495854     False           1.000000

Transferred players flagged for manual review (multiplier < 1 = moved to a less defensive side):

,web_name,team_name,position,expected_defcon_points,is_mover,defcon_multiplier
47,Gomes,Aston Villa,MID,16.359903,True,0.833647
36,Guessand,Aston Villa,MID,1.073512,True,0.851253
20,Nelson,Arsenal,MID,2.174205,True,0.867376
269,Grealish,Man City,MID,1.329577,True,0.881830
295,Anderson,Man City,MID,44.952980,True,0.907172
138,Disasi,Chelsea,DEF,0.000000,True,0.907911
50,Garnacho,Aston Villa,MID,0.094095,True,0.926388
373,Senesi,Spurs,DEF,45.847120,True,0.934024
112,Buonanotte,Brighton,MID,0.052465,True,0.952293
124,Struijk,Brighton,DEF,24.104389,True,0.952293
96,Wilson,Brentford,FWD,0.000000,True,1.017619
93,Anthony,Brentford,MID,0.000000,True,1.023573
399,Fernandes,Spurs,MID,30.479001,True,1.025118
268,Elliott,Liverpool,MID,0.014159,True,1.026706
218,Wilson,Leeds,MID,1.612954,True,1.054016
371,Van Hecke,Spurs,DEF,34.828128,True,1.077610
126,Rogers,Chelsea,MID,3.303790,True,1.079461
297,Andrey Santos,Man Utd,MID,8.770467,True,1.086539
372,Tonali,Spurs,MID,16.904293,True,1.092625
296,Tielemans,Man Utd,MID,20.007539,True,1.172876
377,Robertson,Spurs,DEF,0.865982,True,1.187111

In [7]:
from fpl_v2 import optimize

# Optimise over the full pool (GK + outfield) for a single chosen formation.
pool = pipeline.player_pool()
alt = optimize.optimize(pool, formations={'3-4-3': config.FORMATIONS['3-4-3']})
alt.players.sort_values('xPoints', ascending=False)[squad_cols]

                    INFO     Saving cached data to                                                   ]8;id=5178124;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5178125;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\
                             /home/peter/coding/football_stuff/fpl_v2/data/raw/understat_match

[07/26/26 21:17:52] INFO     Saving cached data to                                                   ]8;id=5178130;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5178131;file:///home/peter/coding/football_stuff/.venv/lib/python3.12/site-packages/soccerdata/_common.py#250\250]8;;\
                             /home/peter/coding/football_stuff/fpl_v2/data/raw/understat_match

          web_name  team_name position  cost     xPoints
425           Raya    Arsenal       GK    60  192.322105
241         Virgil  Liverpool      DEF    65  191.928759
0          Gabriel    Arsenal      DEF    80  191.844372
373         Senesi      Spurs      DEF    60  179.720453
294        Haaland   Man City      FWD   155  178.017776
295       Anderson   Man City      MID    65  165.585553
94          Thiago  Brentford      FWD    80  164.150713
140           Enzo    Chelsea      MID    70  159.310519
189         Garner    Everton      MID    60  155.525180
253     Szoboszlai  Liverpool      MID    70  148.554728
237  Calvert-Lewin      Leeds      FWD    60  130.476315